<a href="https://colab.research.google.com/github/mastgm0817/Python/blob/main/submission/mastgm0817/lecture/Ch02/ch02_05_%EB%94%95%EC%85%94%EB%84%88%EB%A6%AC.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 딕셔너리

지금까지 살펴봤던 리스트와 튜플은 값 여러 개를 일렬로 저장할 뿐 값끼리 연관 관계가 없었습니다. 예를 들어 게임 캐릭터의 능력치를 리스트에 저장해보겠습니다.

In [2]:
lux = {
    "health":490,
    "mana":334,
    "melee":550,
    "armor":18.72
}

리스트 lux에서 인덱스 0은 체력, 인덱스 1은 마나, 인덱스 2는 사거리, 인덱스 3은 방어력이라고 했을 때 리스트만 봐서는 각 값이 어떤 능력치인지 쉽게 알기가 힘듭니다.

파이썬에서는 연관된 값을 묶어서 저장하는 용도로 딕셔너리라는 자료형을 제공합니다. 그럼 게임 캐릭터의 능력치를 딕셔너리에 저장해보겠습니다.

In [3]:
lux

{'health': 490, 'mana': 334, 'melee': 550, 'armor': 18.72}

이제 딕셔너리만 봐도 lux라는 캐릭터의 체력(health)은 490, 마나(mana)는 334, 사거리(melee)는 550, 방어력(armor)은 18.72라는 것을 쉽게 알 수 있습니다. 이처럼 딕셔너리는 값마다 이름을 붙여서 저장하는 방식입니다.

즉, 사전(dictionary)에서 단어를 찾듯이 값을 가져올 수 있다고 하여 딕셔너리라고 부릅니다.

이번 유닛부터 딕셔너리를 만드는 방법과 기본 사용 방법을 알아보겠습니다.

## 딕셔너리 만들기

딕셔너리는 { }(중괄호) 안에 키: 값 형식으로 저장하며 각 키와 값은 ,(콤마)로 구분해줍니다.

* `딕셔너리 = {키1: 값1, 키2: 값2}`

In [6]:
# 그럼 키와 값이 4개씩 들어있는 딕셔너리를 만들어보겠습니다.
ability = {'health': 500, 'mana': 350, "attack": 50, "defence":20}
ability

{'health': 500, 'mana': 350, 'attack': 50, 'defence': 20}

딕셔너리는 키를 먼저 지정하고 :(콜론)을 붙여서 값을 표현합니다. 특히 키에는 값을 하나만 지정할 수 있으며 이런 특성을 따서 키-값 쌍(key-value pair)이라 부릅니다(키-값은 1:1 대응).

In [7]:
ability['health']

500

### 키 이름이 중복되면?

NameError: ignored

In [8]:
ability['health'] = 800
ability

{'health': 800, 'mana': 350, 'attack': 50, 'defence': 20}

### 딕셔너리 키의 자료형

딕셔너리의 키는 문자열뿐만 아니라 정수, 실수, 불도 사용할 수 있으며 자료형을 섞어서 사용해도 됩니다. 그리고 값에는 리스트, 딕셔너리 등을 포함하여 모든 자료형을 사용할 수 있습니다.

In [ ]:
ability = {500:'health', 300:'mana', 50:"attack", 20:"defence"}
ability

{500: 'health', 300: 'mana', 50: 'attack', 20: 'defence'}

In [ ]:
# 단, 키에는 리스트와 딕셔너리를 사용할 수 없습니다.


TypeError: ignored

In [ ]:
a = list(range(10))
dic = {"list1":a}

{'list1': [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]}

In [ ]:
# 근데 튜플은 됩니다.
a = tuple(range(0,10))
dic = {a:100}
dic

{(0, 1, 2, 3, 4, 5, 6, 7, 8, 9): 100}

### 빈 딕셔너리 만들기

빈 딕셔너리를 만들 때는 { }만 지정하거나 dict를 사용하면 됩니다. 보통은 { }를 주로 사용합니다.

* `딕셔너리 = {}`
* `딕셔너리 = dict()`

In [ ]:
dict = {}

{}

In [ ]:
a = dict{}

{}

## 딕셔너리의 키에 접근하고 값 할당하기

In [9]:
# 딕셔너리의 키에 접근할 때는 딕셔너리 뒤에 [ ](대괄호)를 사용하며 [ ] 안에 키를 지정해주면 됩니다.
ability['health'] = 490
ability

{'health': 490, 'mana': 350, 'attack': 50, 'defence': 20}

In [13]:
ability["defence"]

20

### 딕셔너리에 키를 지정하지 않으면?

In [12]:
# 딕셔너리에 키를 지정하지 않은 상태는 해당 딕셔너리 전체를 뜻합니다.
# 따라서 다음과 같이 딕셔너리 lux를 출력하면 { }를 포함하여 딕셔너리 전체가 출력됩니다.
ability

{'health': 490, 'mana': 350, 'attack': 50, 'defence': 20}

### 딕셔너리의 키에 값 할당하기

이제 딕셔너리의 키에 값을 할당해보겠습니다. 딕셔너리는 [ ]로 키에 접근한 뒤 값을 할당합니다.
* `딕셔너리[키] = 값`

In [ ]:
ability = {'health': 500, 'mana': 350, "attack": 50, "defence":20}
ability["skill"] = 100
ability["mana"]
ability

{'health': 500, 'mana': 350, 'attack': 50, 'defence': 20, 'skill': 100}

딕셔너리에서 키의 값을 출력할 때와 마찬가지로 [ ]에 키를 지정한 뒤 값을 할당하면 됩니다. 특히 딕셔너리는 없는 키에 값을 할당하면 해당 키가 추가되고 값이 할당됩니다.

In [15]:
ability['health'] = 2037
ability['mana'] = 1184
ability['melee'] = 550
ability['armor'] = 18.72
ability['mana_regen'] = 3.28

ability

{'health': 2037,
 'mana': 1184,
 'attack': 50,
 'defence': 20,
 'melee': 550,
 'armor': 18.72,
 'mana_regen': 3.28}

In [ ]:
# 그럼 없는 키에서 값을 가져오려고 하면 어떻게 될까요?
ability = {'health': 500, 'mana': 350, "attack": 50, "defence":20}
"health" in ability

True

### 딕셔너리에 키가 있는지 확인하기

딕셔너리에서 키가 있는지 확인하고 싶다면 in 연산자를 사용하면 됩니다.

* `키 in 딕셔너리`

In [17]:
'health' in ability

True

이처럼 딕셔너리에 특정 키가 있으면 True, 없으면 False가 나옵니다. 딕셔너리 lux에 키 'health'가 있으므로 True, 'attack_speed'가 없으므로 False가 나왔습니다.

반대로 in 앞에 not을 붙이면 특정 키가 없는지 확인합니다.

In [19]:
'pw' not in ability

True

### 해시

딕셔너리는 해시(Hash) 기법을 이용해서 데이터를 저장합니다. 보통 딕셔너리와 같은 키-값 형태의 자료형을 해시, 해시 맵, 해시테이블 등으로 부르기도 합니다.

### 딕셔너리의 키 개수 구하기

딕셔너리를 사용하다 보면 딕셔너리의 키 개수(길이)를 구할 필요가 있습니다. 딕셔너리의 키와 값을 직접 타이핑할 때는 키의 개수를 알기가 쉽습니다. 하지만 실무에서는 함수 등을 사용해서 딕셔너리를 생성하거나 키를 추가하기 때문에 키의 개수가 눈에 보이지 않습니다. 따라서 다음과 같이 키의 개수는 len 함수를 사용하여 구합니다(키와 값은 1:1 관계이므로 키의 개수는 곧 값의 개수입니다).

* `len(딕셔너리)`

In [ ]:
ability = {'health': 500, 'mana': 350, "attack": 50, "defence":20}
a = len(ability)
a

4

In [20]:
b = len(ability)
b

7